name: Install Testkube to EKS cluster

on:
  workflow_dispatch:

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

    - name: Install Testkube CLI
      run: |
        curl -sSLf https://get.testkube.io | sh
        testkube pro init --agent-token=tkcagnt_1beb76ac7e1d25696e17ccb4289616 --org-id=tkcorg_1fb88f6e8c51bd20 --env-id=tkcenv_601193720b17f38b
        
    - name: Install Testkube on EKS cluster
      run: |
        kubectl-testkube install --namespace testkube --yes
