name: Provision EKS & Install Testkube

on:
  workflow_dispatch:

jobs:
  setup-eks-and-testkube:
    runs-on: ubuntu-latest

    env:
      STACK_NAME: my-eks-cluster
      TEMPLATE_FILE: cloudformation/stacktemplate.yml
      CLUSTER_NAME: MyEKSCluster
      REGION: ${{ secrets.AWS_REGION }}
      EC2_KEY_NAME: ${{ secrets.EC2_KEY_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create or update CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file $TEMPLATE_FILE \
            --stack-name $STACK_NAME \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ${{ secrets.AWS_REGION }} \
            --no-fail-on-empty-changeset
            --parameter-overrides KeyName="$EC2_KEY_NAME"

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name $CLUSTER_NAME \
            --region ${{ secrets.AWS_REGION }}
