name: Run EKS tests with Testkube

on:
  #push:
    #branches: [ main ]
  #pull_request:
    workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Interact with Testkube
        uses: kubeshop/setup-testkube@v1
        with:
          organization: tkcorg_1fb88f6e8c51bd20
          environment: tkcenv_280a6a0f17801dd1
          token: tkcenv_bc4015c0514c214b_join_token

      - name: Create workflow    
        run: |
          testkube create testworkflow -f k8s/test_deployment.yaml

      - name: Run tests
        run: |
          testkube run testworkflow my-docker-tests -f
